databases:
  - name: dpg-cnqbfg4f7o1s73fmrkq0-a
    plan: free
    databaseName: gamegeek_4pqw
    user: gamegeek_4pqw_user
    hostname: dpg-cnqbfg4f7o1s73fmrkq0-a
    port: 5432

services:
  - type: web
    plan: free
    name: GameGeek
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m uvicorn GameGeek.asgi:application"
    envVars:
      - key: postgres://gamegeek_4pqw_user:BRk9et2gBcBgYuibwmoUbhMvb79558KS@dpg-cnqbfg4f7o1s73fmrkq0-a.oregon-postgres.render.com/gamegeek_4pqw
        fromDatabase:
          name: dpg-cnqbfg4f7o1s73fmrkq0-a
          property: connectionString
      - key: django-insecure-@mbefd1*0+tw%a6))7^eiixdo!h8l7k)c*538-_l7h8!gzsw24
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4