# Generated by Django 4.2.5 on 2023-11-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Approved_age_group', models.BooleanField(default=False)),
                ('Age_group', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('Date_joined', models.DateTimeField(auto_now_add=True)),
                ('Accept_conditions', models.BooleanField(default=False)),
            ],
        ),
    ]
