# Generated by Django 4.2.5 on 2023-11-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0003_remove_gguser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gguser',
            name='Age_group',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
