# Generated by Django 4.2.5 on 2023-11-07 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0004_alter_gguser_age_group'),
    ]

    operations = [
    ]
