# Generated by Django 4.2.7 on 2023-11-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0005_auto_20231107_2207"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamesList",
            fields=[
                ("URL", models.TextField()),
                ("Name", models.TextField()),
                ("Icon_URL", models.TextField()),
                ("Average_User_Rating", models.TextField()),
                ("User_Rating_Count", models.TextField()),
                ("Price", models.TextField()),
                ("In_app_Purchases", models.TextField()),
                ("Description", models.TextField()),
                ("Developer", models.TextField()),
                ("Age_Rating", models.TextField()),
                ("Languages", models.TextField()),
                ("Size", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Genres", models.TextField()),
                ("Original_Release_Date", models.TextField()),
                ("Subtitle_Description", models.TextField()),
                ("ID", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
