# Generated by Django 4.2.5 on 2023-11-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0006_gameslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gguser',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
    ]
