# Generated by Django 4.2.5 on 2023-11-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0009_remove_gguser_is_superuser_remove_gguser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='gguser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
