# Generated by Django 4.2.5 on 2023-11-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0010_gguser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gguser',
            name='Approved_age_group',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
