# Generated by Django 4.2.7 on 2023-11-21 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0011_alter_gguser_approved_age_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gguser",
            name="Age_group",
        ),
    ]
