# Generated by Django 4.2.7 on 2023-11-28 20:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0012_remove_gguser_age_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gameslist",
            name="Subtitle_Description",
        ),
    ]
