# Generated by Django 4.2.5 on 2024-01-18 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0013_remove_gameslist_subtitle_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='BackEnd.gameslist')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='BackEnd.gguser')),
            ],
        ),
    ]
