# Generated by Django 4.2.7 on 2024-01-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0013_remove_gameslist_subtitle_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameslist",
            name="Age_Rating",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="gameslist",
            name="Average_User_Rating",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="gameslist",
            name="Developer",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="gameslist",
            name="Icon_URL",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="gameslist",
            name="Name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="gameslist",
            name="Original_Release_Date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="gameslist",
            name="Price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="gameslist",
            name="URL",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="gameslist",
            name="User_Rating_Count",
            field=models.IntegerField(),
        ),
    ]
