# Generated by Django 4.2.5 on 2024-01-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0014_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('User_ID', 'Game_ID')},
        ),
    ]
