# Generated by Django 4.2.5 on 2024-01-18 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0015_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='Game_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.gameslist'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.gguser'),
        ),
    ]
