# Generated by Django 4.2.7 on 2024-01-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0015_alter_gameslist_average_user_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameslist",
            name="Age_Rating",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="gameslist",
            name="Average_User_Rating",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="gameslist",
            name="Developer",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="gameslist",
            name="Icon_URL",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="gameslist",
            name="Name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="gameslist",
            name="Price",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="gameslist",
            name="URL",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="gameslist",
            name="User_Rating_Count",
            field=models.TextField(),
        ),
    ]
