# Generated by Django 4.2.7 on 2024-01-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0016_alter_gameslist_age_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameslist",
            name="Age_Rating",
            field=models.IntegerField(),
        ),
    ]
