# Generated by Django 4.2.7 on 2024-01-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0017_alter_gameslist_age_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameslist",
            name="Age_Rating",
            field=models.TextField(),
        ),
    ]
