# Generated by Django 4.2.5 on 2024-01-23 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0017_alter_favorite_unique_together_and_more'),
        ('BackEnd', '0018_alter_gameslist_age_rating'),
    ]

    operations = [
    ]
