# Generated by Django 4.2.5 on 2024-01-29 17:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0020_visited_remove_favorite_composite_primary_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visited',
            name='Visited_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
