# Generated by Django 4.2.6 on 2024-01-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0022_remove_visited_visited_date_visited_visited_date'),
    ]

    operations = [
    ]
