# Generated by Django 4.2.6 on 2024-02-20 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0022_remove_visited_visited_date_visited_visited_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('Game_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.gameslist')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.gguser')),
            ],
            options={
                'ordering': ['-Timestamp'],
                'unique_together': {('User_ID', 'Game_ID')},
            },
        ),
    ]
