# Generated by Django 4.2.6 on 2024-02-22 22:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0023_recentlyviewed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RecentlyViewed",
        ),
    ]
