# Generated by Django 4.2.7 on 2024-03-26 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0024_delete_recentlyviewed"),
    ]

    operations = [
        migrations.AddField(
            model_name="gguser",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
