# Generated by Django 4.2.5 on 2024-04-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0024_delete_recentlyviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gguser',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
