# Generated by Django 4.2.7 on 2024-04-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0025_gguser_email_confirmed"),
    ]

    operations = [
        migrations.CreateModel(
            name="filtered_games",
            fields=[
                ("URL", models.TextField()),
                ("Name", models.TextField()),
                ("Icon_URL", models.TextField()),
                ("Average_User_Rating", models.TextField()),
                ("User_Rating_Count", models.TextField()),
                ("Price", models.TextField()),
                ("In_app_Purchases", models.TextField()),
                ("Description", models.TextField()),
                ("Developer", models.TextField()),
                ("Age_Rating", models.TextField()),
                ("Languages", models.TextField()),
                ("Size", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Genres", models.TextField()),
                ("Original_Release_Date", models.DateField()),
                ("ID", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="sorted_games",
            fields=[
                ("URL", models.TextField()),
                ("Name", models.TextField()),
                ("Icon_URL", models.TextField()),
                ("Average_User_Rating", models.TextField()),
                ("User_Rating_Count", models.TextField()),
                ("Price", models.TextField()),
                ("In_app_Purchases", models.TextField()),
                ("Description", models.TextField()),
                ("Developer", models.TextField()),
                ("Age_Rating", models.TextField()),
                ("Languages", models.TextField()),
                ("Size", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Genres", models.TextField()),
                ("Original_Release_Date", models.DateField()),
                ("ID", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
