# Generated by Django 4.2.7 on 2024-04-27 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0026_filtered_games_sorted_games"),
    ]

    operations = [
        migrations.CreateModel(
            name="filtered_game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("URL", models.TextField()),
                ("Name", models.TextField()),
                ("Icon_URL", models.TextField()),
                (
                    "ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BackEnd.gameslist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="sorted_game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("URL", models.TextField()),
                ("Name", models.TextField()),
                ("Icon_URL", models.TextField()),
                (
                    "ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="BackEnd.gameslist",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="filtered_games",
        ),
        migrations.DeleteModel(
            name="sorted_games",
        ),
    ]
