# Generated by Django 4.2.7 on 2024-04-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0028_filtered_games_sorted_games_remove_sorted_game_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sorted_Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("URL", models.TextField()),
                ("Name", models.TextField()),
                ("Icon_URL", models.TextField()),
                ("ID", models.IntegerField()),
                ("Average_User_Rating", models.TextField()),
                ("User_Rating_Count", models.TextField()),
                ("Price", models.TextField()),
                ("In_app_Purchases", models.TextField()),
                ("Description", models.TextField()),
                ("Developer", models.TextField()),
                ("Age_Rating", models.TextField()),
                ("Languages", models.TextField()),
                ("Size", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Genres", models.TextField()),
                ("Original_Release_Date", models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name="Filtered_Games",
            new_name="Filtered_Game",
        ),
        migrations.DeleteModel(
            name="Sorted_Games",
        ),
    ]
