# Generated by Django 4.2.7 on 2024-04-27 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0029_sorted_game_rename_filtered_games_filtered_game_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sorted_game",
            name="Age_Rating",
        ),
        migrations.RemoveField(
            model_name="sorted_game",
            name="Average_User_Rating",
        ),
        migrations.RemoveField(
            model_name="sorted_game",
            name="Description",
        ),
        migrations.RemoveField(
            model_name="sorted_game",
            name="Developer",
        ),
        migrations.RemoveField(
            model_name="sorted_game",
            name="Genres",
        ),
        migrations.RemoveField(
            model_name="sorted_game",
            name="In_app_Purchases",
        ),
        migrations.RemoveField(
            model_name="sorted_game",
            name="Languages",
        ),
        migrations.RemoveField(
            model_name="sorted_game",
            name="Original_Release_Date",
        ),
        migrations.RemoveField(
            model_name="sorted_game",
            name="Price",
        ),
        migrations.RemoveField(
            model_name="sorted_game",
            name="Size",
        ),
        migrations.RemoveField(
            model_name="sorted_game",
            name="User_Rating_Count",
        ),
    ]
