# Generated by Django 4.2.5 on 2024-04-30 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BackEnd", "0030_remove_sorted_game_age_rating_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Filtered_Game",
        ),
        migrations.DeleteModel(
            name="Sorted_Game",
        ),
    ]
