# Generated by Django 4.2.5 on 2024-04-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BackEnd", "0031_delete_filtered_game_delete_sorted_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="gguser",
            name="Security_answer",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="gguser",
            name="Security_question",
            field=models.CharField(
                blank=True,
                choices=[
                    ("city", "What city were you born in?"),
                    ("school", "What elementary school did you attend?"),
                    ("show", "What is the name of your favorite show growing up?"),
                    ("teacher", "What is the name of your favorite childhood teacher?"),
                    ("friend", "What was the name of your favorite childhood friend?"),
                ],
                max_length=50,
            ),
        ),
    ]
