# Generated by Django 4.2.5 on 2024-04-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BackEnd", "0032_gguser_security_answer_gguser_security_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gguser",
            name="Security_question",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
