# Generated by Django 4.2.6 on 2024-04-30 22:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("BackEnd", "0023_auto_20240130_1234"),
        ("BackEnd", "0033_alter_gguser_security_question"),
    ]

    operations = []
