# Generated by Django 4.2.5 on 2024-05-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BackEnd", "0034_merge_20240430_2224"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gguser",
            name="First_name",
        ),
        migrations.RemoveField(
            model_name="gguser",
            name="Last_name",
        ),
    ]
