# Generated by Django 4.2.5 on 2024-05-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BackEnd", "0035_remove_gguser_first_name_remove_gguser_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gguser",
            name="Approved_age_group",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="gguser",
            name="Security_answer",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="gguser",
            name="Security_question",
            field=models.CharField(max_length=255),
        ),
    ]
