# Generated by Django 4.2.7 on 2023-11-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Games",
            fields=[
                ("Game_ID", models.AutoField(primary_key=True, serialize=False)),
                ("URL", models.CharField(max_length=255)),
                ("Name", models.CharField(max_length=255)),
                ("Icon_URL", models.CharField(max_length=255)),
                ("Average_user_rating", models.CharField(max_length=10, null=True)),
                (
                    "User_rating_count",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("Price", models.CharField(max_length=255)),
                ("In_app_purchases", models.CharField(max_length=255)),
                ("Description", models.TextField()),
                ("Developer", models.CharField(max_length=255)),
                ("Age_rating", models.CharField(max_length=10)),
                ("Languages", models.CharField(max_length=255)),
                ("Size", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Genres", models.CharField(max_length=255)),
                ("Original_release_date", models.DateField()),
            ],
        ),
    ]
